# Generated by Django 6.0.5 on 2026-05-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='social_network',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_acc_list', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
