# Generated by Django 6.0.5 on 2026-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_socialnetwork_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='uuid',
        ),
    ]
