# Generated by Django 6.0.5 on 2026-06-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_author_full_name_alter_book_add_user_and_more'),
        ('users', '0005_remove_socialnetwork_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='product.book'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
