# Generated by Django 6.0.5 on 2026-05-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_author_book_bookimage_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='add_user',
        ),
    ]
