# Generated by Django 5.2.9 on 2026-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_book_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='bookimage',
            table='book',
        ),
    ]
