# Generated by Django 6.0.5 on 2026-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_author_full_name_alter_book_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.JSONField(default={'name': 'name'}),
        ),
    ]
