# Generated by Django 6.0.5 on 2026-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_book_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
